version: '3.9'

services:
  testevue:
    container_name: testevue
    image: node:20.11.1-alpine
    volumes:
      - ./:/src/app
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
    ports:
      - 8000:5173
    command: tail -f /dev/null
    working_dir: /src/app
    networks:
      - local
networks:
  local:
    name: local
